### ISSUE TITLE
Unable to login after importing in Bonita 7.8.1

### ISSUE THREAD

**Issue by NunoPinho** [Bonitasoft-Community/vacation-management-example#9]
Hi,

1. I imported the example into Bonita Studio and it imported successfully.
2. I opened the Example-InitiateVacationAvailable diagram and clicked in RUN.
3. Now I can not login into the application, it says: 
"Login failed. No profile has been set up for this user. Contact your administrator." 

I tried with **walter.bates** and with **helen.kelly**.
What is the problem?

**Comment by smcpoland** [comment]
Do you have an organisation in place?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by NunoPinho** [comment]
Hi, @smcpoland 
The default one from Bonita

**Comment by amottier** [comment]
Can you try to:

- Go in Organization -> Deploy... menu
- Select the "ACME" organization and make sure default username is: walter.bates
- Click on "Deploy" button
- Click on the Portal button
- Go in Server -> Open Portal menu

You should be logged in in Bonita Portal with the user walter.bates. If this fail can you share the Studio and Engine logs files available in the Studio "Help" menu?

If you can successfully open the Portal:

- Open the process diagram
- Select the process pool
- Go in Server -> Configure menu
- In "Actor mapping " make sure that "Employee actor" is mapped to /acme group
- In "Authentication" make sure that username is walter.bates and password is bpm

If you still have some issue please share Studio and Engine log files. In order to have a shorter (and simpler to understand log file) you might want to close the Studio, go in Studio workspace\.metadata folder (it might be hidden), delete the .log and tomcat.log files (they might be hidden) and restart the Studio.

**Comment by NunoPinho** [comment]
Hi @amottier 
I just deployed the organization without making any changes and it started working fine.
Thanks for the help, you may close this issue.

**Comment by oamaya7** [comment]
I'm having this exact problem, I just installed Bonita, and tried to Run a process with everything by default, and I always get following message: "Attempt to login with user walter.bates has failed! Please check that his user exists in the active organization and/or that the password is correct in your run configuration of Pool (1.0).".

Can someone please help? I'm trying to do the Bootcamp but I can't get past this.

I'm attaching my log files.
[tomcat.log](https://github.com/Bonitasoft-Community/vacation-management-example/files/9261624/tomcat.log)
[ui-designer.log](https://github.com/Bonitasoft-Community/vacation-management-example/files/9261625/ui-designer.log)

**Comment by sathish0625** [comment]
dsf
